XWikiObj(function (obj) {
    obj.setAuthor("XWiki.Admin");
    obj.setComment("This sheet is pretty complex. Here it is a description of how it works:\n\n1. For every layer we generate a box that contains all the relevant artifact that can be associated to a layer. These are basically all the RiskModelClass objects that are associated to the layer.\n1. The box will contain the following elements, each one identified by an id:\n11. A file upload input type. Its id can be arbitrary but we chose to use \"upload:layer\" (e.g., \"upload:OSS Component\"). This input has a layer attribute that is used to link it to a div whose id must be \"riskModels:THEVALUEOFHTELAYERATTRIBUTE\"\n11. A div where the list of the uploaded model will be displayed. Its id is in the form: \"riskModels:layer\" where \"layer\" is the same used as layer attribute for 2.1\n11. A Javascript that will create the needed hidden inputs for saving the uploaded model names in the correspon RiskModelClass objects. It's interesting how this Javascript knows about the ids to use: when the page is generated, the number of the currently define RiskModelClass objects is calculated and stored in an input field whose id is \"nextRiskModelObjectNumber\". The Javascript will create object ids starting from this number.\n\nOutside the box there are the following elements defined:\n\n1. A hidden input whose id is \"uploadTargetURL\" that is used to communicate to the JavaScript script where to upload the files. We need to put this here because if we put $doc.getURL('upload') in the JavaScript we end up with the URL of the sheet, instead of that of the document\n1. A hidden input for enabling the updateOrCreate object policy\n1. An invisible div which is used to make the html5uploader not to display anything after the upload is finished\n1. An input field whose id is \"nextRiskModelObjectNumber\" used to tell the Javascript code which object id must be used as a starting point\n\n----\n\nHow it works:\n\n1. The script iterates on every layer\n1. For each layer the box is generated. This box basic contains all the information for filling the fields of RISCOSSPlatformRiskConfigurationManagerCode.LayerRiskConfigurationClass\n1. The JavaScript is initialized and all the file inputs are bound to the html5uploader\n1. The id of the different inputs/span are used to link things together. So when an upload triggered by an input whose id is \"X\" finishes, then the name of the uploaded file will be added using an hidden input in the corresponding div\n1. When everything is completed and the user saves the document then a RISCOSSPlatformRiskConfigurationManagerCode.RiskModelClass object for every layer is created with the proper information stored in the corresponding fields (thanks to the object policy updateOrCreate)\n");
    obj.setDate("0");
    obj.setHighlight("");
    obj.setOriginalSelection("");
    obj.setReplyto("");
    obj.setSelection("");
    obj.setSelectionLeftContext("");
    obj.setSelectionRightContext("");
    obj.setState("");
    obj.setTarget("");
});
