XWikiObj(function (obj) {
    obj.setAccessibility("0");
    obj.setAdmin_email("");
    obj.setAuthenticate_edit("1");
    obj.setAuthenticate_view("0");
    obj.setColorTheme("ColorThemes.RISCOSS");
    obj.setComment_anonymous("---");
    obj.setComment_registered("---");
    obj.setConfirmation_email_content("#set ($wikiname = $request.serverName)\n#set ($host = ${request.getRequestURL()})\n#set ($host = ${host.substring(0, ${host.indexOf('/', ${mathtool.add(${host.indexOf('//')}, 2)})})})\nSubject: Your account on ${wikiname} has been activated\n\nHello ${xwiki.getUserName(\"$xwikiname\", false)},\n\nYour account on ${wikiname} has been successfully activated. You can now login at ${host}${xwiki.getURL('XWiki.XWikiLogin', 'login')} using your username (${xwiki.getDocument($xwikiname).getName()}).");
    obj['setCore.defaultDocumentSyntax']("xwiki/2.1");
    obj.setDateformat("");
    obj.setDefault_language("en");
    obj.setDocumentBundles("");
    obj.setEdit_anonymous("---");
    obj.setEdit_registered("---");
    obj.setEditcomment(false);
    obj.setEditcomment_mandatory(false);
    obj.setEditor("Wysiwyg");
    obj.setGuest_comment_requires_captcha(false);
    obj.setInvitation_email_content("");
    obj.setJavamail_extra_props("");
    obj.setLanguages("en");
    obj.setLdap(false);
    obj.setLdap_UID_attr("");
    obj.setLdap_base_DN("");
    obj.setLdap_bind_DN("");
    obj.setLdap_bind_pass("");
    obj.setLdap_exclude_group("");
    obj.setLdap_fields_mapping("");
    obj.setLdap_group_mapping("");
    obj.setLdap_groupcache_expiration("");
    obj.setLdap_mode_group_sync("always");
    obj.setLdap_port("");
    obj.setLdap_server("");
    obj.setLdap_trylocal(false);
    obj.setLdap_update_user(false);
    obj.setLdap_user_group("");
    obj.setLdap_validate_password(false);
    obj.setLeftPanels("");
    obj.setMeta("<meta name=\"revisit-after\" content=\"7 days\" />\n<meta name=\"description\" content=\"$escapetool.xml($!tdoc.plainTitle)\" />\n#set($keywords = \"wiki,$!doc.getTags()\")\n<meta name=\"keywords\" content=\"$escapetool.xml($keywords.replaceAll('[|,]', ' ').trim())\" />\n<meta name=\"distribution\" content=\"GLOBAL\" />\n<meta name=\"rating\" content=\"General\" />\n<meta name=\"author\" content=\"$escapetool.xml($!xwiki.getUserName($doc.getAuthor(), false))\" />\n<meta http-equiv=\"reply-to\" content=\"\" />\n<meta name=\"language\" content=\"$!xcontext.language\" />\n## We verify that we don't display RSS feeds on the login page since it causes problems if these feeds are\n## protected. In addition it makes the login redirect to the feeds page in some cases.\n#if($doc.fullName != \"XWiki.XWikiLogin\")\n<link rel=\"alternate\" type=\"application/rss+xml\" title=\"Wiki Feed RSS\" href=\"$xwiki.getURL('Main.WebRss', 'view', 'xpage=rdf')\" />\n<link rel=\"alternate\" type=\"application/rss+xml\" title=\"Blog RSS Feed\" href=\"$xwiki.getURL('Blog.GlobalBlogRss', 'view', 'xpage=plain')\" />\n#end");
    obj.setMinoredit(false);
    obj.setMultilingual("0");
    obj.setObfuscateEmailAddresses("0");
    obj.setParent("");
    obj.setPlugins("");
    obj.setRegistration_anonymous("---");
    obj.setRegistration_registered("---");
    obj.setRightPanels("Panels.Applications,Panels.QuickLinks,Panels.MyRecentModifications");
    obj.setShowLeftPanels("0");
    obj.setShowRightPanels("0");
    obj.setShowannotations("0");
    obj.setShowattachments("0");
    obj.setShowcomments("0");
    obj.setShowhistory("0");
    obj.setShowinformation("0");
    obj.setSkin("XWiki.DefaultSkin");
    obj.setSmtp_port("");
    obj.setSmtp_server("127.0.0.1");
    obj.setSmtp_server_password("");
    obj.setSmtp_server_username("");
    obj.setStylesheet("style.css");
    obj.setStylesheets("style.css");
    obj.setTags(false);
    obj.setTimezone("");
    obj.setTitle("$tdoc.getRenderedTitle(\"plain/1.0\") ($doc.fullName) - XWiki");
    obj.setUpload_maxsize("67108864");
    obj.setValidation_email_content("#set ($wikiname = $request.serverName)\n#set ($host = ${request.getRequestURL()})\n#set ($host = ${host.substring(0, ${host.indexOf('/', ${mathtool.add(${host.indexOf('//')}, 2)})})})\nSubject: Validate your account on ${wikiname}\n\nHello ${xwiki.getUserName(\"XWiki.$xwikiname\", false)},\n\nThis email address was used to register a new account on ${wikiname}. If you did not make the request, please ignore this message.\n\nIn order to activate your account, please follow this link:\n${host}${xwiki.getURL('XWiki.AccountValidation', 'view', \"validkey=${validkey}&xwikiname=${xwikiname}\")}");
    obj.setVersion("RISCOSS Platform Version 0.24");
    obj.setWebcopyright("© 2012-2014 <a href=\"http://www.riscoss.eu\">RISCOSS</a> Consortium");
    obj['setXwiki.title.mandatory']("0");
});
